### ISSUE TITLE
try it out

### ISSUE THREAD

**Issue by eksten** [futin/tribal-wars-2-admin#3]
Hey,

So i found your project a couple of months back, i understand it isent complete but is there a way to take it out for a testrun? :)

**Comment by futin** [comment]
Hi @eksten, It is actually complete and I've been using it for months now :) I was just too lazy to write documentation for it.

I promise that soon I will write documentation on how to use everything.

But basically, I've split logic in 2 sections: **tw** (tribal-wars-2 logic) and **server** (my custom server which calls **tw** methods). 

You can either try (even though it might be hard without documentation) to use my server (which is using GraphQL) or you can build your own server and simply call the **tw** methods the same way I am doing.

Or you can test the **tw** by manually triggering methods without any server (which is again hard without docs).

Thanks for showing interest!

**Comment by eksten** [comment]
Hey man, thx for the reply.

Well thats the way it usally is, documents always comes last lol. Im a bit of a noob so i can probly dont test anything without a little how-to guide lol. Dont even know how to get it started, so i guess ill have to wait for the documentation :(

**Comment by futin** [comment]
Setup documentation done

**Comment by eksten** [comment]
Hey,

Awsome, just tryed installing but got this error:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

in log file this:

2005 verbose stack Error: An unknown git error occurred
2005 verbose stack     at makeError (C:\Users\nicla\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
2005 verbose stack     at C:\Users\nicla\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
2005 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2006 verbose cwd C:\Users\nicla\Desktop\futin\tribal-wars-2-admin-develop
2007 verbose Windows_NT 10.0.19044
2008 verbose node v16.14.2
2009 verbose npm  v8.10.0
2010 error code ENOENT
2011 error syscall spawn git
2012 error path git
2013 error errno -4058
2014 error enoent An unknown git error occurred
2015 error enoent This is related to npm not being able to find a file.
2015 error enoent
2016 verbose exit -4058
2017 timing npm Completed in 3788ms
2018 verbose unfinished npm timer reify 1652892940510
2019 verbose unfinished npm timer reify:loadTrees 1652892940523
2020 verbose code -4058
2021 error A complete log of this run can be found in:
2021 error     C:\Users\nicla\AppData\Local\npm-cache\_logs\2022-05-18T16_55_40_308Z-debug-0.log

and if i try to start the server this error comes:

 tribal-wars-2-admin@1.9.0 dev
> node lib/index.js

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'axios' imported from C:\Users\nicla\Desktop\futin\tribal-wars-2-admin-develop\lib\index.js
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:932:9)
    at moduleResolve (node:internal/modules/esm/resolve:978:18)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'

**Comment by futin** [comment]
Hey,

I am not sure what is wrong here. I tested on both MacOS and Windows10 + I
have working instance running on Heroku server without any issues.

Make sure that you don't change the name of the project (I see that you
stored it under `tribal-wars-2-admin-develop`) or anything else before
running it successfully for the first time.

Cheers

**Comment by eksten** [comment]
hey,

hmm.. under what name should i store it? i just downloaded it as a zip and unziped it as it was :P i tryed removeing develop in the name without success

**Comment by eksten** [comment]
![Skärmklipp](https://user-images.githubusercontent.com/42212888/169139350-d89474fc-8507-4ad8-a0a3-91b742768255.JPG)

looks like this when i run npm run start

**Comment by futin** [comment]
I am usually using `git clone` technique (git clone https://...), but I
just tested it with .zip download, and everything works as expected. I am
also using LTS Node + NPM.

Try removing node modules by running: rm -rf node_modules/
And then installing dependencies again: npm install

Cheers

**Comment by eksten** [comment]
so i finaly got around to put some time into this and i got it installed but i cant fingure out the token part, it is diffrent on each web browser and no one i try works. 

this is basicly the same lines i get from every broswer but the "tokennumbers" are diffrent on each browser so maybe im at the wrong place and look for it? 

42["msg",{"type":"Authentication/login","data":{"name":"xxxxx","token":"tokennumbers","tokenEmit":"xxxxxxx","userAgent":"browser"},"id":1,"headers":{"traveltimes":[["browser_send",xxxxxxx]]}}
![Skärmklipp](https://user-images.githubusercontent.com/42212888/180600654-8d070d72-c67d-4beb-9426-d03902c6a028.JPG)
]
